<?php

namespace Database\Seeders;

use App\Models\Church;
use Illuminate\Database\Seeder;

class ChurchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* ID: 01 */ Church::create(['id'=>1,   'name'=>'Master','pastor'=>null,'leader'=>null,'zip_code'=>null,'street'=>null,'number'=>null,'complement'=>null,'neighborhood'=>null,'city'=>null,'state'=>null,'email'=>null,'phone'=>null,'mobile_phone'=>null]);

        /* ID: 02 */ Church::create(['id'=>2,   'name'=>'Primeira Igreja Batista no Ingá',                                   'pastor'=>'Pr. Edimar Guimarães Pereira', 'leader'=>'Pra. Evelise Cavalcante', 'zip_code'=>'24210445',   'street'=>'Rua Dr. Paulo Alves',                'number'=>'125',              'neighborhood'=>'Ingá',                  'city'=>'Niterói',               'state'=>'RJ','email'=>'secretaria@pibinga.org.br',            'phone'=>'21 2621 1268',    'mobile_phone'=>'21 98494 5914' ]);
        /* ID: 03 */ Church::create(['id'=>3,   'name'=>'Igreja Batista em Dom Felipe',                                      'pastor'=>'Hilderaldo Pereira',           'leader'=>NULL,                      'zip_code'=>'24942-395',  'street'=>'Rua A',                              'number'=>NULL,                'neighborhood'=>'Inoã',                 'city'=>'Maricá',                'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 04 */ Church::create(['id'=>4,   'name'=>'Primeira Igreja Batista em Cachoeiras de Maricá',                   'pastor'=>'João Rodrigues de A. Filho',   'leader'=>NULL,                      'zip_code'=>'24931-150',  'street'=>'Estrada Joaquim Afonso Viana',       'number'=>'24',                'neighborhood'=>'São José do Imbassaí', 'city'=>'Maricá',                'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 05 */ Church::create(['id'=>5,   'name'=>'Primeira Igreja Batista na Ilha da Conceição',                      'pastor'=>'Paulo Telles',                 'leader'=>NULL,                      'zip_code'=>'24050-000',  'street'=>'Rua Dep Cordeiro Miranda',           'number'=>'121',               'neighborhood'=>'Ilha da Conceição',    'city'=>'Niteroi',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 06 */ Church::create(['id'=>6,   'name'=>'Igreja Pentecostal do Poder',                                       'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 07 */ Church::create(['id'=>7,   'name'=>'Centro Evangelístico Ministério Ide',                               'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>'24942285',   'street'=>'Rua Caio de Figueiredo',             'number'=>'355',               'neighborhood'=>'Inoã (Inoã)',          'city'=>'Maricá',                'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 08 */ Church::create(['id'=>8,   'name'=>'Igreja Congregacional do Retiro',                                   'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 09 */ Church::create(['id'=>9,   'name'=>'Primeira Igreja Batista em Heliópolis',                             'pastor'=>'Davidson Pereira de Freitas',  'leader'=>NULL,                      'zip_code'=>'26140000',   'street'=>'Avenida Júlio de Amorim Pereira',    'number'=>'116',               'neighborhood'=>'Heliópolis',           'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 10 */ Church::create(['id'=>10,  'name'=>'Primeira Igreja Batista no Bairro das Graças',                      'pastor'=>'Cláudio Silva de Mello',       'leader'=>NULL,                      'zip_code'=>'26113-415',  'street'=>'Avenida Joaquim da Costa Lima',      'number'=>'654',               'neighborhood'=>'Das Graças',           'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 11 */ Church::create(['id'=>11,  'name'=>'Igreja Batista em Vila Nova',                                       'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 12 */ Church::create(['id'=>12,  'name'=>'Primeira Igreja Batista no Barreto',                                'pastor'=>'Pr. Samuel Mouta',             'leader'=>'Thadeu Martini',          'zip_code'=>'24110-305',  'street'=>'Rua Guimarães Júnior',               'number'=>'58',                'neighborhood'=>'Barreto',              'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>'21 2624 1075',              'mobile_phone'=>null ]);
        /* ID: 13 */ Church::create(['id'=>13,  'name'=>'Igreja Batista Central em Andrade Araújo',                          'pastor'=>'Alfredo',                      'leader'=>NULL,                      'zip_code'=>'26135342',   'street'=>'Rua Castro Alves',                   'number'=>'764',               'neighborhood'=>'Andrade Araujo',       'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 14 */ Church::create(['id'=>14,  'name'=>'Igreja Cristã Evangélica Renovada',                                 'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 15 */ Church::create(['id'=>15,  'name'=>'Igreja Batista Ebenézer em Santa Luzia',                            'pastor'=>'Joab Pereira',                 'leader'=>NULL,                      'zip_code'=>'24722-800',  'street'=>'Rua Francisco Vieira',               'number'=>'4',                 'neighborhood'=>'Santa Luzia',          'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 16 */ Church::create(['id'=>16,  'name'=>'Segunda Igreja Batista de Vista Alegre',                            'pastor'=>'Carlos Roberto',               'leader'=>NULL,                      'zip_code'=>'24736-150',  'street'=>'Rua São João da Madeira',            'number'=>NULL,                'neighborhood'=>'Vista Alegre',         'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 17 */ Church::create(['id'=>17,  'name'=>'Primeira Igreja Batista da Marambaia',                              'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>'24727-280',  'street'=>'Rua da Fraternidade',                'number'=>NULL,                'neighborhood'=>'Marambaia',            'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 18 */ Church::create(['id'=>18,  'name'=>'Primeira Igreja Batista Santa Amélia',                              'pastor'=>'Jonas Sales',                  'leader'=>NULL,                      'zip_code'=>'26115-110',  'street'=>'Rua Deocacina Almeida Affonso',      'number'=>'12',                'neighborhood'=>'Nova Piam',            'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 19 */ Church::create(['id'=>19,  'name'=>'Comunidade Evangélica do Nazareno',                                 'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>'26123-120',  'street'=>'Rua Sérgio João Pereira',            'number'=>'481',               'neighborhood'=>'Heliópolis',           'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 20 */ Church::create(['id'=>20,  'name'=>'Primeira Igreja Batista em Jardim Xavantes',                        'pastor'=>'Ricardo de Jesus',             'leader'=>NULL,                      'zip_code'=>'26160-160',  'street'=>'Rua Biquiba',                        'number'=>'1',                 'neighborhood'=>'Jardim Xavante',       'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 21 */ Church::create(['id'=>21,  'name'=>'Primeira Igreja Batista em Santa Amélia',                           'pastor'=>'Jonas Sales',                  'leader'=>NULL,                      'zip_code'=>'26115-110',  'street'=>'Rua Casuarinas',                     'number'=>'12',                'neighborhood'=>'Ambaí',                'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 22 */ Church::create(['id'=>22,  'name'=>'Primeira Igreja Batista em Boqueirão de Rio Bonito',                'pastor'=>'Cornélio Augusto',             'leader'=>NULL,                      'zip_code'=>'28800-000',  'street'=>'Rua Munir Abdala Helayel,',          'number'=>NULL,                'neighborhood'=>'Boqueirão',            'city'=>'Rio Bonito',            'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 23 */ Church::create(['id'=>23,  'name'=>'Primeira Igreja Batista em Rio do Ouro',                            'pastor'=>'Sirley',                       'leader'=>NULL,                      'zip_code'=>'24330-000',  'street'=>'Estrada Velha de Maricá',            'number'=>'282',               'neighborhood'=>'Rio do Ouro',          'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 24 */ Church::create(['id'=>24,  'name'=>'Ministério Apostólico Peniel Aldeia da Prata',                      'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 25 */ Church::create(['id'=>25,  'name'=>'Igreja Evangélica Assembleia de Deus Manancial de Vida',            'pastor'=>'Denizard Rivail Pedrosa',      'leader'=>NULL,                      'zip_code'=>'24340-105',  'street'=>'Avenida Central Ewerton Xavier',     'number'=>NULL,                'neighborhood'=>'Itaipu',               'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 26 */ Church::create(['id'=>26,  'name'=>'Igreja Batista na Colônia Z-10',                                    'pastor'=>'Pr. Fabio Pereira',            'leader'=>NULL,                      'zip_code'=>'21930600',   'street'=>'Rua Teodoro Sales',                  'number'=>'11',                'neighborhood'=>'Ribeira',              'city'=>'Rio de Janeiro',        'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 27 */ Church::create(['id'=>27,  'name'=>'Terceira Igreja Batista em Areia Branca',                           'pastor'=>'Marcos Lúcio de Jesus Silva',  'leader'=>NULL,                      'zip_code'=>'26135-000',  'street'=>'Rua José da Cunha',                  'number'=>'131',               'neighborhood'=>'Areia Branca',         'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 28 */ Church::create(['id'=>29,  'name'=>'Primeira Igreja Batista Jardim Marileia Rio das Ostras',            'pastor'=>'Pr. Fábio Marinho',            'leader'=>NULL,                      'zip_code'=>'28895895',   'street'=>'Rua Barra do Piraí',                 'number'=>NULL,                'neighborhood'=>'Jardim Mariléa',       'city'=>'Rio das Ostras',        'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 29 */ Church::create(['id'=>30,  'name'=>'Igreja Batista Ebenézer',                                           'pastor'=>'Marco Antonio Pinto',          'leader'=>NULL,                      'zip_code'=>'26012370',   'street'=>'Rua Quinze de Novembro',             'number'=>'775',               'neighborhood'=>'Viga',                 'city'=>'Nova Iguaçu',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 30 */ Church::create(['id'=>31,  'name'=>'Primeira Igreja Batista em Cordeiro',                               'pastor'=>'Beniltom Cezar Santos',        'leader'=>NULL,                      'zip_code'=>'28540-000',  'street'=>'Rua Manoel Mussi',                   'number'=>'98',                'neighborhood'=>'Santa Tereza',         'city'=>'Cordeiro',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 31 */ Church::create(['id'=>32,  'name'=>'Primeira Igreja Batista em Vila Rosali',                            'pastor'=>'Alfredo Ricardo Machado',      'leader'=>NULL,                      'zip_code'=>'25510-152',  'street'=>'Avenida Doutor Rúbens Farrula',      'number'=>'270',               'neighborhood'=>'Vila Rosali',          'city'=>'São João de Meriti',    'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 32 */ Church::create(['id'=>33,  'name'=>'Primeira Igreja Batista em Silva Jardim',                           'pastor'=>'Pr. Alex Porto Vargas',        'leader'=>NULL,                      'zip_code'=>'28820-000',  'street'=>'Av. Luís Gomes',                     'number'=>'782',               'neighborhood'=>'Centro',               'city'=>'Silva Jardim',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 33 */ Church::create(['id'=>34,  'name'=>'Igreja Batista Jardim Ouro Preto',                                  'pastor'=>'Leonardo Bohrer Schittino',    'leader'=>NULL,                      'zip_code'=>'28895895',   'street'=>'Rua João de Souza',                  'number'=>'893',               'neighborhood'=>'Jardim Ouro Preto',    'city'=>'Nova Friburgo',         'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 34 */ Church::create(['id'=>35,  'name'=>'Igreja Batista no Engenho Velho',                                   'pastor'=>'Diniz Ferreira Maia',          'leader'=>NULL,                      'zip_code'=>'24805627',   'street'=>'Rua Doze',                           'number'=>'Lote 147',          'neighborhood'=>'Engenho Velho',        'city'=>'Itaboraí',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 35 */ Church::create(['id'=>36,  'name'=>'Igreja de Nova Vida de Ceilândia',                                  'pastor'=>'Filemon Teófilo Silva',        'leader'=>NULL,                      'zip_code'=>'72215-032',  'street'=>'QNM 3 Conjunto B',                   'number'=>'Lote 3',            'neighborhood'=>'Ceilândia Sul',        'city'=>'Brasília',              'state'=>'DF','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 36 */ Church::create(['id'=>37,  'name'=>'Igreja Metodista Wesleyana Central em Itaboraí',                    'pastor'=>'Ivan Alves Rodrigues',         'leader'=>NULL,                      'zip_code'=>'24800-089',  'street'=>'Rua Presidente Castelo Branco',      'number'=>'1509',              'neighborhood'=>'Centro',               'city'=>'Itaboraí',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 37 */ Church::create(['id'=>38,  'name'=>'Igreja Metodista Wesleyana de Itaúna',                              'pastor'=>'Pr. Ricardo Pimentel',         'leader'=>NULL,                      'zip_code'=>'24474-005',  'street'=>'Estrada Trindade',                   'number'=>'2004',              'neighborhood'=>'Itaúna',               'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 38 */ Church::create(['id'=>39,  'name'=>'Igreja Metodista Wesleyana Rio Várzea',                             'pastor'=>'Cezar Melo',                   'leader'=>NULL,                      'zip_code'=>'24808-068',  'street'=>'Rua Maria Duarte de Almeida',        'number'=>'30',                'neighborhood'=>'Ampliação',            'city'=>'Itaboraí',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 39 */ Church::create(['id'=>40,  'name'=>'Igreja Metodista Wesleyana de Porto das Caixas',                    'pastor'=>'Leonardo dos Santos',          'leader'=>NULL,                      'zip_code'=>'24830-116',  'street'=>'Rua Amazonas',                       'number'=>'137',               'neighborhood'=>'Centro',               'city'=>'Itaboraí',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 40 */ Church::create(['id'=>41,  'name'=>'Segunda Igreja Batista de Itaboraí',                                'pastor'=>'Orbílio Ribeiro',              'leader'=>NULL,                      'zip_code'=>'24808-064',  'street'=>'Avenida Papa João XXIII',            'number'=>'36',                'neighborhood'=>'Ampliação',            'city'=>'Itaboraí',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 41 */ Church::create(['id'=>42,  'name'=>'Igreja Bíblica Cristã',                                             'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 42 */ Church::create(['id'=>43,  'name'=>'Igreja Pentecostal Vida Plena',                                     'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 43 */ Church::create(['id'=>44,  'name'=>'Igreja Pentecostal Mão no Arado Ministério Getsêmani',              'pastor'=>'Daniel Pereira',               'leader'=>NULL,                      'zip_code'=>'24436-000',  'street'=>'Rua Abílio José de Matos',           'number'=>'2412',              'neighborhood'=>'Porto da Pedra',       'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 44 */ Church::create(['id'=>45,  'name'=>'Assembleia de Deus Central de Itaboraí',                            'pastor'=>'Enéas',                        'leader'=>NULL,                      'zip_code'=>'24800-025',  'street'=>'Avenida Amélia Saraiva',             'number'=>'408',               'neighborhood'=>'Centro',               'city'=>'Itaboraí',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 45 */ Church::create(['id'=>46,  'name'=>'Igreja Batista em Leandro',                                         'pastor'=>'Ciro César da Costa',          'leader'=>NULL,                      'zip_code'=>'23830-250',  'street'=>'Estrada Engenheiro Ivan Mundin',     'number'=>'43',                'neighborhood'=>'Mazomba',              'city'=>'Itaguaí',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 46 */ Church::create(['id'=>47,  'name'=>'Igreja Metodista Ortodoxa em Brisamar',                             'pastor'=>'Júlio Martins',                'leader'=>NULL,                      'zip_code'=>'23825-620',  'street'=>'Rua Manoel Rodrigues Pereira',       'number'=>'10',                'neighborhood'=>'Brisa Mar',            'city'=>'Itaguaí',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 47 */ Church::create(['id'=>48,  'name'=>'Primeira Igreja Batista em Vila Margarida',                         'pastor'=>'Lucas Anunciação Padilha',     'leader'=>NULL,                      'zip_code'=>'23821-580',  'street'=>'Rua Manoel de Souza Pinto',          'number'=>'26',                'neighborhood'=>'Vila Margarida',       'city'=>'Itaguaí',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 48 */ Church::create(['id'=>49,  'name'=>'Primeira Igreja Batista em Vila Geni',                              'pastor'=>'Moisés Gonçalves Ferreira',    'leader'=>NULL,                      'zip_code'=>'23825-780',  'street'=>'Rua Presidente Roosevelt',           'number'=>'490',               'neighborhood'=>'Vila Geny',            'city'=>'Itaguaí',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 49 */ Church::create(['id'=>50,  'name'=>'Primeira Igreja Batista de São João da Barra',                      'pastor'=>'Maximiliano Gomes Fernandes',  'leader'=>NULL,                      'zip_code'=>'28200000',   'street'=>'Rua Largo do Moreira',               'number'=>'69',                'neighborhood'=>'Centro',               'city'=>'São João da Barra',     'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 50 */ Church::create(['id'=>51,  'name'=>'Igreja Batista Filadélfia de Niterói',                              'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>'24110-678',  'street'=>'Josué da Silva Andrade',             'number'=>NULL,                'neighborhood'=>'Caramujo',             'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 51 */ Church::create(['id'=>52,  'name'=>'Congregação Batista em Japeri',                                     'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>'Japeri',               'city'=>'Rio de Janeiro',        'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 52 */ Church::create(['id'=>53,  'name'=>'Igreja Batista Renascer',                                           'pastor'=>'Renato Silva de Oliveira',     'leader'=>NULL,                      'zip_code'=>'26381408',   'street'=>'Rua Conde Aljezur',                  'number'=>'12',                'neighborhood'=>'Do Carmo',             'city'=>'Queimados',             'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 53 */ Church::create(['id'=>54,  'name'=>'Primeira Igreja Batista de Macaé',                                  'pastor'=>'Robson Melo Câmara',           'leader'=>NULL,                      'zip_code'=>'27910070',   'street'=>'Rua Tenente-Coronel Amado',          'number'=>'203',               'neighborhood'=>'Centro',               'city'=>'Macaé',                 'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 54 */ Church::create(['id'=>55,  'name'=>'Primeira Igreja Batista em Seropédica',                             'pastor'=>'Evaldo Rocha',                 'leader'=>NULL,                      'zip_code'=>'23890000',   'street'=>'Av. Min. Fernando Costa',            'number'=>'737',               'neighborhood'=>'Fazenda Caxias',       'city'=>'Seropédica',            'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 55 */ Church::create(['id'=>56,  'name'=>'Igreja Batista em Nova Cidade',                                     'pastor'=>'Daniel Gomes de Miranda',      'leader'=>NULL,                      'zip_code'=>'24445300',   'street'=>'Rua Doutor Nilo Peçanha',            'number'=>'1002',              'neighborhood'=>'Antonina',             'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 56 */ Church::create(['id'=>57,  'name'=>'Terceira Igreja Batista Central em Santa Izabel',                   'pastor'=>'Paulo Giovani',                'leader'=>NULL,                      'zip_code'=>'24732-000',  'street'=>'Rua Santa Rita',                     'number'=>'19',                'neighborhood'=>'Santa Izabel',         'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 57 */ Church::create(['id'=>58,  'name'=>'Igreja Batista em Imbaú',                                           'pastor'=>'Gessé Pereira de Souza Júnior','leader'=>NULL,                      'zip_code'=>'28820-000',  'street'=>'Rua José de Souza Herdy',            'number'=>NULL,                'neighborhood'=>'Centro',               'city'=>'Silva Jardim',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 58 */ Church::create(['id'=>59,  'name'=>'Primeira Igreja Batista em Avelar',                                 'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 59 */ Church::create(['id'=>60,  'name'=>'Igreja Presbiteriana Filadélfia em Ariquemes',                      'pastor'=>'Everson Ferreira Cunha',       'leader'=>NULL,                      'zip_code'=>'76870 000',  'street'=>'Avenida Jaru',                       'number'=>'2450',              'neighborhood'=>'Setor 3',              'city'=>'Ariquemes',             'state'=>'RO','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 60 */ Church::create(['id'=>61,  'name'=>'Primeira Igreja Presbiteriana de Porto Velho',                      'pastor'=>'Autair Emerick',               'leader'=>NULL,                      'zip_code'=>'76804-236',  'street'=>'Rua Almirante Barroso',              'number'=>'1180',              'neighborhood'=>'Santa Bárbara',        'city'=>'Porto Velho',           'state'=>'RO','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 61 */ Church::create(['id'=>62,  'name'=>'Igreja Batista em Jardim Gláucia',                                  'pastor'=>'Antonio Marcos',               'leader'=>NULL,                      'zip_code'=>'26195-140',  'street'=>'Rua Péricles',                       'number'=>'1',                 'neighborhood'=>'Jardim Glaucia',       'city'=>'Belford Roxo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 62 */ Church::create(['id'=>63,  'name'=>'Congregação de Manilha da Igreja Batista Vinte e Dois de Novembro', 'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>'Itaboraí',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 63 */ Church::create(['id'=>64,  'name'=>'Congregação Presbiteriana de Candeias do Jamari',                   'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>'76860-000',  'street'=>'Avenida Tancredo Neves',             'number'=>'2131',              'neighborhood'=>'Novo Horizonte',       'city'=>'Candeias do Jamari',    'state'=>'RO','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 64 */ Church::create(['id'=>65,  'name'=>'Segunda Igreja Batista em Cabo Frio',                               'pastor'=>'Hudson Galdino da Silva',      'leader'=>NULL,                      'zip_code'=>'28910-010',  'street'=>'Rua Elpídio Barbosa Guimarães',      'number'=>'59',                'neighborhood'=>'Jardim Caiçara',       'city'=>'Cabo Frio',             'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 65 */ Church::create(['id'=>66,  'name'=>'Congregação da PIBN em Trindade São Gonçalo',                       'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 66 */ Church::create(['id'=>67,  'name'=>'Primeira Igreja Batista de Niterói',                                'pastor'=>'José Laurindo Filho',          'leader'=>'Pr. Cleverson Rodrigues', 'zip_code'=>'24030-210',  'street'=>'Rua Marquês do Paraná',              'number'=>'225',               'neighborhood'=>'Centro',               'city'=>'Niterói',               'state'=>'RJ','email'=>'secretaria@pibn.org.br',               'phone'=>'21 2722 0355',    'mobile_phone'=>null ]);
        /* ID: 67 */ Church::create(['id'=>68,  'name'=>'Igreja Presbiteriana Barra Funda',                                  'pastor'=>'Rev. Mauro Meister',           'leader'=>NULL,                      'zip_code'=>'01140-000',  'street'=>'Avenida Thomás Edison',              'number'=>'320',               'neighborhood'=>'Barra Funda',          'city'=>'São Paulo',             'state'=>'SP','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 68 */ Church::create(['id'=>69,  'name'=>'Primeira igreja Batista em Conquista',                              'pastor'=>'Haroldo do Amaral Carvalho',   'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 69 */ Church::create(['id'=>70,  'name'=>'Primeira Igreja Batista em Brasilândia',                            'pastor'=>'Pr Dario de Oliveira',         'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>'Rua Minas Gerais',                   'number'=>'637',               'neighborhood'=>'Brasilândia',          'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 70 */ Church::create(['id'=>71,  'name'=>'Igreja Batista da amizade',                                         'pastor'=>NULL,                           'leader'=>NULL,                      'zip_code'=>'24630-560',  'street'=>'Rua Araxá',                          'number'=>NULL,                'neighborhood'=>'Trindade',             'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 71 */ Church::create(['id'=>72,  'name'=>'Primeira Igreja Batista de Coroa Grande',                           'pastor'=>'Efigênio Batista Junior',      'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>NULL,                    'state'=>NULL,'email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 72 */ Church::create(['id'=>73,  'name'=>'Departamento de Evangelismo e Missões',                             'pastor'=>'Pr. Daniel Cunta',             'leader'=>NULL,                      'zip_code'=>'24210145',   'street'=>'Rua Visconde de Moraes',             'number'=>'231',               'neighborhood'=>'Ingá',                 'city'=>'Niterói',               'state'=>'RJ','email'=>'evangelismo@batistafluminense.org.br', 'phone'=>'21 2620 1515 ',   'mobile_phone'=>'21 99600 6130' ]);
        /* ID: 73 */ Church::create(['id'=>74,  'name'=>'Igreja Batista em Santa Cruz',                                      'pastor'=>'Joaquim José da Costa Dias',   'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>'Nova Fiburgo',          'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 74 */ Church::create(['id'=>75,  'name'=>'Igreja Batista no Catarcione',                                      'pastor'=>'Jakson dos Santos Araújo',     'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>'Catarcione',           'city'=>'Nova Friburgo',         'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 75 */ Church::create(['id'=>76,  'name'=>'Primeira Igreja Batista em Campo do Coelho',                        'pastor'=>'Haniel Moura Bastos',          'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>'Campo do Coelho',      'city'=>'Nova Friburgo',         'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 76 */ Church::create(['id'=>77,  'name'=>'Terceira Igreja Batista em Cordeiro',                               'pastor'=>'Wagner Gomes Bastos',          'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>'Cordeiro',              'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 77 */ Church::create(['id'=>78,  'name'=>'Primeira Igreja Batista em São Sebastião do Alto',                  'pastor'=>'Jorge Carlos Barbosa Teófilo', 'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>'48',                'neighborhood'=>NULL,                   'city'=>'São Sebastião do Alto', 'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 78 */ Church::create(['id'=>79,  'name'=>'Primeira Igreja Batista em Pinheiros',                              'pastor'=>'Wagner Poubel da Silva',       'leader'=>NULL,                      'zip_code'=>'29980-000',  'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>'Pinheiros',             'state'=>'ES','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 79 */ Church::create(['id'=>80,  'name'=>'Igreja Batista Ministério Reviver',                                 'pastor'=>'Gerson Antonio Furtado',       'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>NULL,                   'city'=>'Angra dos Reis',        'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 80 */ Church::create(['id'=>81,  'name'=>'Igreja Batista em Jerônimo  Afonso',                                'pastor'=>'Sebastião Figueiredo',         'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>NULL,                                 'number'=>NULL,                'neighborhood'=>'Jerônimo Afonso',      'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 81 */ Church::create(['id'=>83,  'name'=>'Igreja Batista em Euclidelândia',                                   'pastor'=>'José Carlos Barbosa Teófilo',  'leader'=>NULL,                      'zip_code'=>'28500-000',  'street'=>'Rua Joaquim Píres Purina',           'number'=>NULL,                'neighborhood'=>'Vila Saint Clair',     'city'=>'Cantagalo',             'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 82 */ Church::create(['id'=>84,  'name'=>'Primeira Igreja Batista em Carmo',                                  'pastor'=>'Fabrício Beira Pires',         'leader'=>NULL,                      'zip_code'=>'28640-000',  'street'=>'Rua Luiz de Moura Pinheiro',         'number'=>'188',               'neighborhood'=>'Centro',               'city'=>'Carmo',                 'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 83 */ Church::create(['id'=>85,  'name'=>'Primeira Igreja Batista em Paraty',                                 'pastor'=>'Pedro Elizio da Silva Duarte', 'leader'=>NULL,                      'zip_code'=>'23970-000',  'street'=>'Avenida Roberto Silveira',           'number'=>'493',               'neighborhood'=>'Centro',               'city'=>'Paraty',                'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 84 */ Church::create(['id'=>86,  'name'=>'Igreja Batista Vida',                                               'pastor'=>'Renato G. Souza de Oliveira',  'leader'=>NULL,                      'zip_code'=>'23946-235',  'street'=>'Rua do Cartório',                    'number'=>'81',                'neighborhood'=>'Frade',                'city'=>'Angra dos Reis',        'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 85 */ Church::create(['id'=>87,  'name'=>'Igreja Batista Central em Japuíba',                                 'pastor'=>'Ezequias Amancio Marins',      'leader'=>NULL,                      'zip_code'=>'23934 -695', 'street'=>'Rua Prefeito João Gregório Galindo', 'number'=>'6.400',             'neighborhood'=>NULL,                   'city'=>'Angra dos Reis',        'state'=>'RJ','email'=>'secretaria@ibacen.com.br',             'phone'=>'24 3367 0741',    'mobile_phone'=>'24 99301 2610' ]);
        /* ID: 86 */ Church::create(['id'=>88,  'name'=>'Igreja Batista Vinte e Dois de Novembro',                           'pastor'=>'Felipe Rei',                   'leader'=>NULL,                      'zip_code'=>'24120-049',  'street'=>'Avenida 22 de Novembro',             'number'=>'90',                'neighborhood'=>'Fonseca',              'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 87 */ Church::create(['id'=>89,  'name'=>'Igreja Batista Memorial em Niterói',                                'pastor'=>'Fábio Tinoco Vieira',          'leader'=>NULL,                      'zip_code'=>'24120-135',  'street'=>'Rua Padre Leandro',                  'number'=>'36',                'neighborhood'=>'Ponto Cem Reis',       'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 88 */ Church::create(['id'=>90,  'name'=>'Igreja Evangélica Missão Resplandecer',                             'pastor'=>'Claudio Martins',              'leader'=>NULL,                      'zip_code'=>'24426-430',  'street'=>'Rua João Batista',                   'number'=>'78',                'neighborhood'=>'Porto Velho',          'city'=>'São Gonçalo',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 89 */ Church::create(['id'=>91,  'name'=>'Segunda Igreja Batista em São João do Paraíso',                     'pastor'=>'Anderson Coutinho Navarro',    'leader'=>NULL,                      'zip_code'=>'28450 000',  'street'=>'Rua Capitão Tavares',                'number'=>'208',               'neighborhood'=>'São João do Paraíso',  'city'=>'Cambuci',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 90 */ Church::create(['id'=>93,  'name'=>'Segunda Igreja Batista em Conselheiro Josino',                      'pastor'=>'José Antonio Cabral de Souza', 'leader'=>NULL,                      'zip_code'=>'28.165-971', 'street'=>'Rua 3',                              'number'=>'s/n',               'neighborhood'=>'Bairro Parabólica',    'city'=>'Campos dos Goitacazes', 'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 91 */ Church::create(['id'=>94,  'name'=>'Primeira Igreja Batista em Mangaratiba',                            'pastor'=>'Leonardo Alves de Almeida',    'leader'=>NULL,                      'zip_code'=>'23860 000',  'street'=>'Estrada RJ',                         'number'=>'14',                'neighborhood'=>'Centro',               'city'=>'Mangaratiba',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 92 */ Church::create(['id'=>96,  'name'=>'Igreja Evangélica Congregacional de Magaratiba',                    'pastor'=>'Alberto Carlos Alegria',       'leader'=>NULL,                      'zip_code'=>'23800-000',  'street'=>'Rua Variante Raul Gouveia',          'number'=>'405',               'neighborhood'=>'Ibicuí',               'city'=>'Mangaratiba',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 93 */ Church::create(['id'=>97,  'name'=>'Igreja Assembleia de Deus - Ministério Amar',                       'pastor'=>'Pr. Cirlei Correa',            'leader'=>NULL,                      'zip_code'=>'24130-088',  'street'=>'Av. Prof. João Brasil',              'number'=>'89',                'neighborhood'=>'Fonseca',              'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 94 */ Church::create(['id'=>98,  'name'=>'Segunda Igreja Batista São João do Paraíso',                        'pastor'=>'Anderson Coutinho Navarro',    'leader'=>NULL,                      'zip_code'=>'28450-000',  'street'=>'Rua Capitão Tavares',                'number'=>'208',               'neighborhood'=>'São João do Paraíso',  'city'=>'Cambuci',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 95 */ Church::create(['id'=>99,  'name'=>'Igreja Batista Vida Vitoriosa',                                     'pastor'=>'Cristiano Suzano de Mattos',   'leader'=>NULL,                      'zip_code'=>'28897-174',  'street'=>'Rua Dinah Silveira de Queiroz',      'number'=>'328',               'neighborhood'=>'Enseada das Gaivotas', 'city'=>'Rio das Ostras',        'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 96 */ Church::create(['id'=>100, 'name'=>'Comunidade Evangélica Tabernáculo de Davi',                         'pastor'=>'Adilson Roberto da Conceição', 'leader'=>NULL,                      'zip_code'=>'25211-250',  'street'=>'Rua Gonçalves Magalhães',            'number'=>'Quadra 65 Lote 11', 'neighborhood'=>NULL,                   'city'=>'Duque de Caxias',       'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 97 */ Church::create(['id'=>101, 'name'=>'Igreja Batista Memorial em São Fidélis',                            'pastor'=>'Denis Alves Pinto',            'leader'=>NULL,                      'zip_code'=>'28400-000',  'street'=>'Rua Francisco Calomeni',             'number'=>'41',                'neighborhood'=>'Vila dos Coroados',    'city'=>'São Fidélis',           'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 98 */ Church::create(['id'=>102, 'name'=>'Primeira Igreja Batista no Caramujo',                               'pastor'=>'Pr. Jailton Barreto Rangel',   'leader'=>NULL,                      'zip_code'=>NULL,         'street'=>'R. Dr. Nilo Pecanha',                'number'=>'846',               'neighborhood'=>'Caramujo',             'city'=>'Niterói',               'state'=>'RJ','email'=>null,                                   'phone'=>null,              'mobile_phone'=>null ]);
        /* ID: 99 */ Church::create(['id'=>103, 'name'=>'Primeira Igreja Batista de Atlanta',                                'pastor'=>'Dr. Anthony George',           'leader'=>NULL,                      'zip_code'=>'30338',      'street'=>'Peachtree Rd',                       'number'=>'4400',              'neighborhood'=>NULL,                   'city'=>'Atlanta',               'state'=>'GA']);
    }
}
