<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoleUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DN
        DB::table('role_user')->insert(['user_id'=>1,'role_id'=>1]);
        DB::table('role_user')->insert(['user_id'=>4,'role_id'=>1]);
        //Admin
        DB::table('role_user')->insert(['user_id'=>1,'role_id'=>2]);
        DB::table('role_user')->insert(['user_id'=>4,'role_id'=>2]);
        DB::table('role_user')->insert(['user_id'=>5,'role_id'=>2]);
        //FW
        DB::table('role_user')->insert(['user_id'=>1,'role_id'=>3]);
        DB::table('role_user')->insert(['user_id'=>2,'role_id'=>3]);
        DB::table('role_user')->insert(['user_id'=>3,'role_id'=>3]);
        DB::table('role_user')->insert(['user_id'=>4,'role_id'=>3]);
        //F.EE
        DB::table('role_user')->insert(['user_id'=>1,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>2,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>3,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>4,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>5,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>3,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>8,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>37,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>53,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>57,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>67,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>81,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>84,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>87,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>91,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>93,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>107,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>117,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>135,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>146,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>160,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>178,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>180,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>183,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>193,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>204,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>223,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>229,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>231,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>240,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>259,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>261,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>266,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>273,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>286,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>289,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>292,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>293,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>298,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>306,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>309,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>319,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>320,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>330,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>332,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>342,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>351,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>353,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>363,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>370,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>406,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>407,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>410,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>417,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>424,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>441,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>451,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>454,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>471,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>478,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>479,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>481,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>116,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>38,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>423,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>450,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>230,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>304,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>297,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>350,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>470,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>177,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>179,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>203,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>222,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>228,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>239,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>260,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>285,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>352,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>477,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>134,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>159,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>182,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>192,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>258,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>265,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>291,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>308,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>329,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>331,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>405,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>440,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>453,'role_id'=>4]);
        DB::table('role_user')->insert(['user_id'=>480,'role_id'=>4]);
        //F.EPC
        DB::table('role_user')->insert(['user_id'=>1,'role_id'=>5]);
        DB::table('role_user')->insert(['user_id'=>2,'role_id'=>5]);
        DB::table('role_user')->insert(['user_id'=>3,'role_id'=>5]);
        DB::table('role_user')->insert(['user_id'=>4,'role_id'=>5]);
        DB::table('role_user')->insert(['user_id'=>5,'role_id'=>5]);
        DB::table('role_user')->insert(['user_id'=>6,'role_id'=>5]);
        //P.WESM
        DB::table('role_user')->insert(['user_id'=>1,'role_id'=>6]);
        DB::table('role_user')->insert(['user_id'=>2,'role_id'=>6]);
        DB::table('role_user')->insert(['user_id'=>3,'role_id'=>6]);
        DB::table('role_user')->insert(['user_id'=>5,'role_id'=>6]);
        //P.CEE
        DB::table('role_user')->insert(['user_id'=>1,'role_id'=>7]);
        DB::table('role_user')->insert(['user_id'=>2,'role_id'=>7]);
        DB::table('role_user')->insert(['user_id'=>3,'role_id'=>7]);
        //P.WEPC
        DB::table('role_user')->insert(['user_id'=>1,'role_id'=>8]);
        DB::table('role_user')->insert(['user_id'=>2,'role_id'=>8]);
        DB::table('role_user')->insert(['user_id'=>6,'role_id'=>8]);
    }
}
